"""Firmware source generation from a duplex matrix wiring.

Generates QMK and/or ZMK firmware files that reflect the duplex (square)
matrix wiring produced by klepcbgen. Both firmwares support bidirectional
(direct) duplex scanning.
"""
import os

from klepcbgenmod import CONTROLLER_PINS


def _sanitize(name):
    """Lowercase, alnum-only firmware-safe identifier."""
    return "".join(c for c in name.lower() if c.isalnum() or c == "_")


def _matrix_rows(keys):
    """Return a list of (keynum, legend, a, b) tuples for all keys."""
    return [(k.num, k.legend, k.matrix_a, k.matrix_b) for k in keys]


def generate_qmk(outdir, keyboard, options):
    """Write QMK config.h + keymap.c for a duplex matrix."""
    rows = _matrix_rows(keyboard.keys)
    lines = keyboard.matrix_lines
    pins = CONTROLLER_PINS[options.controller]

    # config.h: matrix size + direct pins. QMK treats duplex lines as direct
    # pins, so DIODE_DIRECTION is not used; we define DIRECT_PINS instead.
    cfg = []
    cfg.append("/* Generated by klepcbgen. Duplex (square) matrix. */")
    cfg.append(f"#pragma once")
    cfg.append("")
    cfg.append(f"#define MATRIX_ROWS {lines}")
    cfg.append(f"#define MATRIX_COLS {lines}")
    cfg.append("")
    cfg.append("/* Duplex: all lines are bidirectional direct pins. */")
    cfg.append("#define DIRECT_PINS { \\")
    for i in range(lines):
        comma = "," if i < lines - 1 else ""
        cfg.append(f"    {{ {pins[i]} }}{comma} \\")
    cfg.append("}")
    cfg.append("")

    # keymap.c: a 1:1 map from the flattened duplex layout.
    km = []
    km.append("/* Generated by klepcbgen. Duplex (square) matrix. */")
    km.append("#include QMK_KEYBOARD_H")
    km.append("")
    km.append("const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {")
    km.append("    [0] = {")
    # Build a matrix of keycodes; only cells that map to a real key get a code.
    cell = {}
    for knum, legend, a, b in rows:
        cell[(a, b)] = f"KC_{_keycode(legend)}"
    for a in range(lines):
        rowcells = []
        for b in range(lines):
            if b <= a:
                rowcells.append("KC_NO")
            else:
                rowcells.append(cell.get((a, b), "KC_NO"))
        km.append("        " + ", ".join(rowcells) + ",")
    km.append("    },")
    km.append("};")
    km.append("")

    with open(os.path.join(outdir, "config.h"), "w") as f:
        f.write("\n".join(cfg))
    with open(os.path.join(outdir, "keymap.c"), "w") as f:
        f.write("\n".join(km))


def generate_zmk(outdir, keyboard, options):
    """Write ZMK .keymap + .overlay for a duplex matrix."""
    rows = _matrix_rows(keyboard.keys)
    lines = keyboard.matrix_lines

    # ZMK uses a transform / direct scan. For a duplex (square) matrix we emit
    # a keymap that references each key by its (a,b) pair. ZMK's direct GPIO
    # driver needs the binding list; we represent each key as a row-col pos.
    parts = []
    parts.append("/* Generated by klepcbgen. Duplex (square) matrix. */")
    parts.append("/ {")
    parts.append("    compatible = \"zmk,keymap\";")
    parts.append("    default_layer {")
    parts.append("        bindings = <")
    for knum, legend, a, b in rows:
        parts.append(f"            &kp {_keycode(legend)}")
    parts.append("        >;")
    parts.append("    };")
    parts.append("};")
    parts.append("")

    with open(os.path.join(outdir, "default.keymap"), "w") as f:
        f.write("\n".join(parts))


def _keycode(legend):
    """Map a key legend to a QMK/ZMK keycode. Falls back to a placeholder for
       unknown legends; a full KLE->keycode mapping is out of scope here."""
    mapping = {
        "Esc": "ESC", "Tab": "TAB", "Caps Lock": "CAPS", "Shift": "LSFT",
        "Ctrl": "LCTL", "Win": "LGUI", "Alt": "LALT", "Space": "SPC",
        "Enter": "ENT", "Backspace": "BSPC", "Delete": "DEL",
        "PgUp": "PGUP", "PgDn": "PGDN", "Home": "HOME", "End": "END",
        "Insert": "INS",
    }
    if legend in mapping:
        return mapping[legend]
    # Single letters / digits map directly
    if len(legend) == 1 and legend.isalpha():
        return legend.upper()
    if len(legend) == 1 and legend.isdigit():
        return "N" + legend
    # F-keys
    if legend.startswith("F") and legend[1:].isdigit():
        return "F" + legend[1:]
    # Fallback
    return "NO"
