(fp_lib_table
  (version 7)
  (lib (name "Button_Switch_Keyboard")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Button_Switch_Keyboard.pretty")(options "")(descr "Keyboard switch footprints"))
  (lib (name "Button_Switch_SMD")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Button_Switch_SMD.pretty")(options "")(descr "SMD switch footprints"))
  (lib (name "Capacitor_SMD")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Capacitor_SMD.pretty")(options "")(descr "SMD capacitor footprints"))
  (lib (name "Connector_PinHeader_2.54mm")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Connector_PinHeader_2.54mm.pretty")(options "")(descr "2.54mm pin header footprints"))
  (lib (name "Connector_USB")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Connector_USB.pretty")(options "")(descr "USB connector footprints"))
  (lib (name "Crystal")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Crystal.pretty")(options "")(descr "Crystal footprints"))
  (lib (name "Diode_SMD")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Diode_SMD.pretty")(options "")(descr "SMD diode footprints"))
  (lib (name "Module")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Module.pretty")(options "")(descr "Module footprints"))
  (lib (name "MountingHole")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/MountingHole.pretty")(options "")(descr "Mounting hole footprints"))
  (lib (name "Package_QFP")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Package_QFP.pretty")(options "")(descr "QFP package footprints"))
  (lib (name "Resistor_SMD")(type "KiCad")(uri "${KICAD9_FOOTPRINT_DIR}/Resistor_SMD.pretty")(options "")(descr "SMD resistor footprints"))
)
