  (module Module:RaspberryPi_Pico_Common_THT (layer B.Cu) (tedit 5A00F000) (tstamp RPIPICO0001)
    (at 0 0)
    (descr "Raspberry Pi Pico module, through-hole headers (2x20)")
    (tags "Raspberry Pi Pico RP2040")
    (path /RPI_PICO)
    (attr smd)
    (fp_text reference U1 (at 0 -3) (layer F.SilkS)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_text value RaspberryPi_Pico (at 0 51) (layer F.Fab)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_line (start -2.54 -2.54) (end 20.32 -2.54) (layer F.CrtYd) (width 0.05))
    (fp_line (start 20.32 -2.54) (end 20.32 50.8) (layer F.CrtYd) (width 0.05))
    (fp_line (start 20.32 50.8) (end -2.54 50.8) (layer F.CrtYd) (width 0.05))
    (fp_line (start -2.54 50.8) (end -2.54 -2.54) (layer F.CrtYd) (width 0.05))
    {% for line in range(matrix_lines) %}
    (pad "{{ line + 1 }}" thru_hole circle (at 0 {{ line * 2.54 }}) (size 1.7 1.7) (drill 1)
      (layers *.Cu *.Mask)
      (net {{ nets.get_net_num("/Matrix_" ~ line) }} /Matrix_{{ line }}))
    {% endfor %}
    (pad "39" thru_hole circle (at 17.78 2.54) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask)
      (net {{ nets.get_net_num("VCC") }} VCC))
    (pad "40" thru_hole circle (at 17.78 0) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask)
      (net {{ nets.get_net_num("GND") }} GND))
    (model ${KISYS3DMOD}/Module.3dshapes/RaspberryPi_Pico.wrl
      (at (xyz 0 0 0))
      (scale (xyz 1 1 1))
      (rotate (xyz 0 0 0))
    )
  )
