  (module Diode_SMD:D_SOD-123 (layer B.Cu) (tedit 5B4B45C8) (tstamp 5E91CDF6)
    (at {{x}} {{y}} {{rotation}})
    (descr "Diode SMD SOD-123")
    (tags "diode SOD-123")
    (path /DIODE_{{num}})
    (attr smd)
    (fp_text reference D{{num}} (at 0 1.65 90) (layer B.SilkS)
      (effects (font (size 1 1) (thickness 0.15)) (justify mirror))
    )
    (fp_text value D (at 0 -1.65 90) (layer B.Fab)
      (effects (font (size 1 1) (thickness 0.15)) (justify mirror))
    )
    (pad 1 smd roundrect (at -1.8 0 90) (size 1.3 2.4) (layers B.Cu B.Paste B.Mask) (roundrect_rratio 0.2)
      (net {{matrix_b_netnum}} {{matrix_b_netname}}))
    (pad 2 smd roundrect (at 1.8 0 90) (size 1.3 2.4) (layers B.Cu B.Paste B.Mask) (roundrect_rratio 0.2)
      (net {{diodenetnum}} {{diodenetname}}))
  )
