  (module Diode_SMD:D_0603_1608Metric_Pad1.08x0.95mm_HandSolder (layer B.Cu) (tedit 5B4B45C8) (tstamp 5E91CDF6)
    (at {{x}} {{y}} 90)
    (descr "Diode SMD 0603 (1608 Metric), hand soldering")
    (tags "diode handsolder")
    (path /DIODE_{{num}})
    (attr smd)
    (fp_text reference D{{num}} (at 0 1.65 90) (layer B.SilkS)
      (effects (font (size 1 1) (thickness 0.15)) (justify mirror))
    )
    (fp_text value D (at 0 -1.65 90) (layer B.Fab)
      (effects (font (size 1 1) (thickness 0.15)) (justify mirror))
    )
    (pad 1 smd roundrect (at -0.8 0 90) (size 0.9 1.1) (layers B.Cu B.Paste B.Mask) (roundrect_rratio 0.25)
      (net {{matrix_b_netnum}} {{matrix_b_netname}}))
    (pad 2 smd roundrect (at 0.8 0 90) (size 0.9 1.1) (layers B.Cu B.Paste B.Mask) (roundrect_rratio 0.25)
      (net {{diodenetnum}} {{diodenetname}}))
  )
