  (module MountingHole:MountingHole_3.5mm (layer F.Cu) (tedit 00000000) (tstamp 5E933001)
    (at {{x}} {{y}})
    (descr "Keyboard stabilizer mounting hole (MX plate-mount), {{size}}u key, at {{side}}")
    (tags "stabilizer stab mounting-hole keyboard")
    (path /STAB_{{num}})
    (attr exclude_from_pos_files exclude_from_bom)
    (fp_text reference STAB{{num}} (at 0 -2.54) (layer F.SilkS)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_text value "STAB" (at 0 2.54) (layer F.Fab)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_line (start -3.5 -0.5) (end 3.5 -0.5) (layer F.SilkS) (width 0.12))
    (fp_line (start 3.5 -0.5) (end 3.5 0.5) (layer F.SilkS) (width 0.12))
    (fp_line (start 3.5 0.5) (end -3.5 0.5) (layer F.SilkS) (width 0.12))
    (fp_line (start -3.5 0.5) (end -3.5 -0.5) (layer F.SilkS) (width 0.12))
    (pad 1 np_thru_hole circle (at 0 0) (size 3.5 3.5) (drill 3.5) (layers *.Cu *.Mask))
    (fp_text user %R (at 0 0) (layer F.Fab)
      (effects (font (size 1 1) (thickness 0.15)))
    )
  )
